version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: api_rest_nestjs
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pg-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8.8
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
      - "5050:80"
    networks:
      - pg-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    user: "${UID}:${GID}"
    restart: unless-stopped

networks:
  pg-network:
    driver: bridge

volumes:
  pgdata:
  pgadmin-data: